### PR TITLE
define should be anonymous

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by mikesamuel** [comment]
Why is an anonymous define preferable?

**Comment by graingert** [comment]
@mikesamuel define should either be anonymous or match the npm name.

**Comment by kevin-brown** [comment]
> Why is an anonymous define preferable?

It makes it very difficult to include a package in your build system if it's not an anonymous define. When it's named, your build system either needs to detect that (it usually doesn't) and alias local imports for you, or you need to explicitly map the defined name to the file location, so you that you can still import it. It actually causes enough issues that there's a dedicated page for RequireJS explaining how to use jQuery with it.

http://requirejs.org/docs/jquery.html

**Comment by mikesamuel** [comment]
Ok.  I see

> So to reiterate, you will likely get an error if you refer to jQuery with another module name, like 'lib/jquery'. This example will not work:

```js
    // THIS WILL NOT WORK
    define(['lib/jquery'], function ($) {...});
```

> It will not work, since jQuery registers itself with the name of 'jquery' and not 'lib/jquery'. **In general, explicitly naming modules in the `define()` call are discouraged, but jQuery has some special constraints.**

**Comment by mikesamuel** [comment]
This looks good to me.  @amroamroamro has a number of large patches in flight so I'm not going to merge yet.  It's much easier to redo a one liner manually than to merge one into a multi-file multi-commit PR.

**Comment by graingert** [comment]
@mikesamuel that's definitionally false. You can transform the problem of `merge A -> B`, into `merge B -> A` with simple operations: `squash(revert B, apply A, merge B -> A, apply B)`;

**Comment by amroamroamro** [comment]
@mikesamuel patches 3 and 4 (demos and tests) are ready to merge if there are no further reviews/comments.
I'm ok if you want to merge this one too next, it won't conflict much. I usually `git rebase` before I submit pull requests anyway.

**Comment by amroamroamro** [comment]
Now I'm thinking out loud, but do we need to keep the `define()`? From what I understand (I'm no expert, so correct if I'm wrong), bundlers and transforming tools have largely made this obsolete (browserify, webpack, rollup, etc.), so perhaps it's not as important anymore...

What is the convention these days regarding module loaders, bundlers, and such? I don't want to propose any major changes for now, just to get an idea.

**Comment by amroamroamro** [comment]
@graingert I remembered, you need to also update the definition in [amd-externs.js](https://github.com/google/code-prettify/blob/master/tools/closure-compiler/amd-externs.js) for this PR, otherwise you'll get a warning from closure-compiler.

**Comment by mikesamuel** [comment]
> @mikesamuel that's definitionally false. You can transform the problem of merge A -> B, into merge B -> A with simple operations: squash(revert B, apply A, merge B -> A, apply B);

I'm not up on DARCS theory of patches, but I do know that if I try to apply a single line patch after merging a change that changes indentation of the block containing it, then I have to do more work.

**Comment by mikesamuel** [comment]
> @mikesamuel patches 3 and 4 (demos and tests) are ready to merge if there are no further reviews/comments.
> I'm ok if you want to merge this one too next, it won't conflict much. I usually git rebase before I submit pull requests anyway.

I'd marked them approved through the code review interface.  I'm happy to do the merge though.

**Comment by amroamroamro** [comment]
@mikesamuel oh noted. I wasn't sure if you wanted me to do the merge, thanks.

**Comment by graingert** [comment]
@mikesamuel glorious. can we get a `.mjs` es-module next?

**Pull request merged**
