### PR TITLE
Package.json for usage with npm

### PR DESCRIPTION
**Pull request by tseabra-rocket**

### CODE REVIEW

**Comment by Pink401k** [comment]
I believe this is missing a `module.exports = prettyPrint;` at the end of the file.  Right now, `var prettyPrint = require('code-prettify');` and then `prettyPrint()` will result in `Uncaught TypeError: prettyPrint is not a function`

**Comment by tseabra-rocket** [comment]
You can use "browser" param on your package.json and it will work.
But you guys should take a look at the jsHint errors there are a lot of them and I was had a lot of trouble compiling this.
thanks

**Comment by mikesamuel** [comment]
Is https://gist.github.com/defunctzombie/4339901 the browser thing you were talking about?

**Comment by Pink401k** [comment]
https://github.com/Pink401k/code-prettify This will work using `npm install` and `prettyPrint = require('code-prettify');`.

I'm using it on a React project now, which is why I wanted to get it to work with just npm and using the module export.

**Comment by philwareham** [comment]
Bumping this - would be very useful to be able to install this package via NPM

**Comment by Pink401k** [comment]
@philwareham If you npm install the repository I linked above, it will work for you until a fix is pulled in for this Repo :)

**Comment by ghpabs** [comment]
It'd be great to have this package in npm.

**Comment by Pink401k** [comment]
@mikesamuel If you check out the changes on my [fork](https://github.com/Pink401k/code-prettify), you can get it working pretty easily.  The big thing is changing the information in the [package.json](https://github.com/Pink401k/code-prettify/blob/master/package.json) To be the information that you would like to display.  Mainly, `author`, `contributors`, `name` and `version`.  You could then run `npm publish` to push it to npm so people can install by running `npm install code-prettify`

https://docs.npmjs.com/cli/publish for more information.

**Comment by amroamroamro** [comment]
added `package.json` in #469

**Comment by alex-milanov** [comment]
#476 I've created a pull request with small changes so that it can be used inside of a npm based pipeline

**Pull request closed without merging**
