### PR TITLE
Allow keys to contain hyphens

### PR DESCRIPTION
**Pull request by clayreimann**
See the [full length example](http://www.yaml.org/spec/1.2/spec.html#id2761803) from the yaml docs.

### CODE REVIEW

**Comment by clayreimann** [comment]
@mikesamuel Ping.

**Comment by clayreimann** [comment]
@mikesamuel [badger, badger](www.youtube.com/watch?v=NL6CDFn2i3I)

**Comment by mikesamuel** [comment]
Thanks.  Sorry for the delay.

**Comment by clayreimann** [comment]
No problem :smile:

**Pull request merged**
