### PR TITLE
Add lexer for the Logtalk programming language

### PR DESCRIPTION
**Pull request by pmoura**

### CODE REVIEW

**Comment by mikesamuel** [comment]
Thanks

**Comment by pmoura** [comment]
Thanks for accepting and merging my lexer contribution. I will do my best to keep it up-to-date.

**Comment by mikesamuel** [comment]
Wonderful.  Thanks for contributing.

**Comment by amroamroamro** [comment]
@pmoura
perhaps you should also add an enty to the list of supported language extensions in the `README.md` file.

**Comment by pmoura** [comment]
Fixed in the #386 pull request.

**Pull request merged**
