### PR TITLE
Markdown fixes

### PR DESCRIPTION
**Pull request by amroamroamro**
Help with the `HTML -> Markdown` conversion:

- a few edits to README.md file
- CHANGES.html converted to Markdown

### CODE REVIEW

**Comment by amroamroamro** [comment]
I noticed that you just removed the `README-zh-Hans.html` file.

For what it's worth, I had already converted it into Markdown. So if you still want to keep it, I can add it to this pull request...

I don't speak Chinese myself, it was just a matter of copy/pasting the text and fixing the Markdown syntax :smiley:

**Comment by vermiculus** [comment]
:+1: though I think you should try squashing these commits :smile:

**Comment by mikesamuel** [comment]
Thanks for doing this.

**Comment by amroamroamro** [comment]
Glad I could help, thanks for merging.

**Pull request merged**
