### PR TITLE
Remove RawGit dependency (jsDelivr+GitHack)

### LINKED ISSUE #422: Use Github Pages instead of Rawgit
Github Pages seems like a good choice for:

https://rawgit.com/google/code-prettify/master/examples/quine.html
https://rawgit.com/google/code-prettify/master/styles/index.html

### LINKED ISSUE #564: repo has dependencies on rawgit, which is shutting down
Rawgit is shutting down around October 2019 [1], and Prettify has dependencies on the site (even if self-hosting the core files, since run_prettify.js relies on it in several areas). Are there plans to transition to a different service?

[1] https://rawgit.com/

### PR DESCRIPTION
**Pull request by ncruces**
This removes the RawGit dependency, which is [winding down](https://rawgit.com/) (fixes #564).

PR #570 suggests using [GitHack](https://raw.githack.com/), which "functions exactly the same."
Unfortunately, #570 doesn't fix the issue [where it really maters](https://github.com/google/code-prettify/blob/453bd5f51e61245339b738b1bbdd42d7848722ba/src/run_prettify.js#L230), see https://github.com/google/code-prettify/issues/564#issuecomment-447660969.

For the actual scripts, I used [jsDelivr](https://www.jsdelivr.com/), which seems to have an [decent backing](https://www.jsdelivr.com/sponsors).

Elsewhere (mostly: samples, documentation) I used GitHack, because jsDelivr does not support serving HTML content with the appropriate Content-Type.
These usages should really be moved to GitHub Pages (would fix #422).
See the next comment for why I didn't use GitHack for everything.

### CODE REVIEW

**Comment by ncruces** [comment]
GitHack, suffers from the same issue RawGit did, which lead to its demise.

Quoting the [website](https://raw.githack.com/#no-uptime-guarantee):

> **I need guaranteed 100% uptime. Should I use raw.githack.com?**
>
> Probably not.
> 
> raw.githack.com is a free service and cannot provide any uptime or support guarantees, even for CDN URLs. While I do my best to keep things running, things sometimes go wrong. Sometimes there are network or provider issues outside my control, sometimes abusive traffic temporarily affects response times, and sometimes I break things (although I try really hard not to).
> 
> Since I run raw.githack.com in my spare time, with my own money and with free CDN hosting by CloudFlare, it has a budget that's probably less than you pay for coffee in a given month. My goal is to help other open source developers get their projects up and running, but if you need to serve files that are crucial to your business, you should probably pay for a host with well-funded infrastructure and uptime guarantees.

Hopefully jsDelivr is reliable enough to [hard code into the source](https://github.com/google/code-prettify/blob/453bd5f51e61245339b738b1bbdd42d7848722ba/src/run_prettify.js#L230).

**Comment by mikesamuel** [comment]
I'll pull this PR locally, check that the generated sources all rebuild nicely, then be ready to merge it into master.

How time sensitive is this?  I'd like to post an announcement to https://groups.google.com/forum/#!forum/js-code-prettifier and give people time to read it and be ready in case there's any trouble.

Ideally this change wouldn't happen over the US holidays when many people are out of the office.

How does landing this change second week of January sound?

**Comment by ncruces** [comment]
I don't think it's time sensitive at all, just something that needs to be fixed, eventually.
RawGit will continue to work until at least October 2019, according to the website.

**Comment by ZhaoTzuHsien** [comment]
That is good.

**Comment by ncruces** [comment]
Is this something that can be looked into soonish?

I have an app that depends on code-prettify and I'd like to know if I can upgrade it with new "official" URLs or if I should just use my own fork.

**Comment by ncruces** [comment]
Nudging @mikesamuel

**Comment by mikesamuel** [comment]
Sending out email to support group now.

**Comment by mikesamuel** [comment]
Announcement at https://groups.google.com/forum/#!topic/js-code-prettifier/IFHev_kLm30

Will add link to README.

**Comment by mikesamuel** [comment]
https://github.com/google/code-prettify/commit/f20e1523dfd916f2502e212ec14e30a27ad50ec9 might introduce a merge conflict with this PR since it cherrypicks this PR's changes to the README and adds a link at the top to the migration announcement.

**Comment by EyalLavi** [comment]
jsdelivr is serving version 0.1.0 of code-prettify, which still references rawgit  (https://www.jsdelivr.com/package/npm/code-prettify). This is probably because there has not been an official release of this repo since this fix was merged. Is there a planned release date for code-prettify before rawgit goes away?

**Comment by ncruces** [comment]
I can confirm the issue. It seems jsdelivr caches things pretty much "forever", which I didn't know. I'm sorry.

There's an [issue](https://github.com/jsdelivr/jsdelivr/issues/18101) tracking that behavior and I'm trying to figure out the best way forward.

**Comment by ncruces** [comment]
OK, so this was a [bug with jsDelivr](https://github.com/jsdelivr/jsdelivr/issues/18101#issuecomment-483304076).
Previously cached URLs have been purged from the CDN (but, obviously, not client devices).

I can confirm all files are now current and being served with:
`cache-control: public, max-age=604800, s-maxage=43200`

So, 7 day private, 12h shared cache. Previously was one year, immutable.

Clients who got the "immutable" cached version need to purge their caches before October.

**Comment by mikesamuel** [comment]
@ncruces Will request access.  Thanks for investigating.

**Pull request merged**
