### PR TITLE
Add `import` and `of` (`for`-`of`) to JSCRIPT_KEYWORDS

### PR DESCRIPTION
**Pull request by mathiasbynens**

### CODE REVIEW

**Comment by amroamroamro** [comment]
FYI the file `src/prettify.js` is generated (combined from multiple files), you should modify `js-modules/prettify.js` instead.
Otherwise changes will be overwritten next time you run `grunt`.

**Comment by mikesamuel** [comment]
@amroamroamro , Good catch.  Will fix.

**Comment by amroamroamro** [comment]
@mikesamuel 
I've seen many PRs here making that mistake..
Perhaps worth creating a [contribution guidelines][1] or a [PR template][2] file to make that clear. And also mention the Google CLA requirement.

[1]: https://help.github.com/articles/setting-guidelines-for-repository-contributors/
[2]: https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

**Comment by mathiasbynens** [comment]
The folder name `src` strongly suggests that this is a source file rather than a generated file. It would also help to rename that.

**Pull request merged**
