### PR TITLE
Added async, await and yield C# keywords support

### PR DESCRIPTION
**Pull request by PedroLamas**
I added these originally in eace8e0c6ea18ff02b7d4dd2bfe61549835a31b4, but it got removed with 7c601842dae2195f0995379111fe262a71a7ca86, so I'm adding them back now!

### CODE REVIEW

**Comment by PedroLamas** [comment]
I signed it!

**Comment by amroamroamro** [comment]
@PedroLamas 
FYI, `src/prettify.js` is auto-generated from the sources in `js-modules/*.js`,
so your changes will be undone when the makefile is rerun.

I suggest you make modifications to files in `js-modules/`.

**Comment by PedroLamas** [comment]
I did these changes on `js-modules/prettify.js`, isn't that where they are supposed to go in?

**Comment by amroamroamro** [comment]
It is, I was talking just about your old commit :)

**Comment by PedroLamas** [comment]
Ah, thanks! Indeed I can say I learned my lesson!! 😄

**Comment by amroamroamro** [comment]
I fixed those mishaps in this last update #467
(there was your PR #418 and also PR #384 which were mistakenly undone).
This is now safe to close, thank you.

**Pull request closed without merging**
