### PR TITLE
Adds keywords from Swift 3.0.1 spec

### PR DESCRIPTION
**Pull request by akerbos**
A couple of new keywords have been introduced to Swift. This adds them to the highlighting spec.

### CODE REVIEW

**Comment by akerbos** [comment]
I won't sign the CLA because I'm not comfortable with typing my home address and phone number into a Google form. I agree with the terms, though, if that counts for anything.

If you can't use this pull request even though it falls, by my estimation, well below the threshold of originality, I'd ask you to review the file in question and re-type the added keywords. What a silly idea...

**Comment by Coeur** [comment]
I see. Well, I signed the agreement for this PullRequest: https://github.com/google/code-prettify/pull/487

**Comment by reitzig** [comment]
Indeed, @Coeur's PR make much of the same changes.

Missing:
 * Literal: `_`
 * Keywords: `throws` `repeat` `where`

And then there's Swift 3.1 and 4.0 to consider.

**Comment by Coeur** [comment]
@reitzig You or I can look at those four missing tokens in a new Pull Request. But the current pull request #466 should be closed as obsolete.

**Pull request closed without merging**
